# Generated by Django 4.2.27 on 2026-02-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_user_last_login_ip_user_last_login_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('incident_type', models.CharField(choices=[('LOGIN_FAILURE', '登录失败'), ('LOGIN_SUCCESS', '登录成功'), ('PERMISSION_DENIED', '权限拒绝'), ('SQL_INJECTION_ATTEMPT', 'SQL注入尝试'), ('XSS_ATTEMPT', 'XSS攻击尝试'), ('CSRF_ATTEMPT', 'CSRF攻击尝试'), ('FILE_UPLOAD_VIOLATION', '文件上传违规'), ('BRUTE_FORCE_ATTEMPT', '暴力破解尝试'), ('UNAUTHORIZED_ACCESS', '未授权访问'), ('SUSPICIOUS_ACTIVITY', '可疑活动')], default='SUSPICIOUS_ACTIVITY', max_length=50)),
                ('level', models.CharField(choices=[('LOW', '低'), ('MEDIUM', '中'), ('HIGH', '高'), ('CRITICAL', '严重')], default='MEDIUM', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('request_url', models.CharField(blank=True, max_length=500, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('additional_data', models.TextField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_by', models.CharField(blank=True, max_length=50, null=True)),
                ('resolved_time', models.DateTimeField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'b_security_event',
                'indexes': [models.Index(fields=['create_time'], name='se_create_time'), models.Index(fields=['incident_type'], name='se_incident_type'), models.Index(fields=['level'], name='se_level')],
            },
        ),
    ]
