# Generated by Django 4.2.27 on 2026-02-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_add_security_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
