# Generated by Django 4.2.27 on 2026-02-16 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_increase_token_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(blank=True, default='email', max_length=20),
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_histories', to='myapp.user')),
            ],
            options={
                'db_table': 'b_password_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=64, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(choices=[('desktop', '桌面设备'), ('mobile', '移动设备'), ('tablet', '平板设备'), ('unknown', '未知设备')], default='unknown', max_length=20)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('login_count', models.IntegerField(default=0)),
                ('is_trusted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='myapp.user')),
            ],
            options={
                'db_table': 'b_user_device',
                'indexes': [models.Index(fields=['user', 'is_active'], name='ud_user_active'), models.Index(fields=['device_id'], name='ud_device_id')],
            },
        ),
    ]
